---
- name: Initial Setup to create ubuntu user
  hosts: all
  become: yes
  
  roles:
    - kubernetes_raspberry_pi_poe
    - ubuntu_user
    - containerd
    - firewall
    - kubernetes_install
    - nfs

- name: Set up master
  hosts: masters
  become: yes

  roles:
    - role: nfs_server
      user: "ubuntu"
      path: "/media/HDD"
    - role: firewall
      ports:
        - '22'
        # # There might be some big mistake with this for nfs.
        - '111' # nfs
        - '2049' # nfs
        - '33333' # nfs
        - '40992' # nfs
        - '51461' # nfs
        - '54623' # nfs
        - '56785' # nfs
        - '35996' # nfs
        - '41205' # nfs
        - '179' # BGP
        - '7946'
        - '6443' # k8s 
        - '2379:2380' # k8s etcd server client API
        - '10250:10252' # kubelet API, kube-scheduler, kube-controller-manager
    - role: kubernetes_single_control_plane
      ip_address: "192.168.1.50"
      user: ubuntu

  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Set up workers
  hosts: workers
  become: yes

  roles:
    - role: firewall
      ports:
        - '22'
        - '179'
        - '7946'
        - '10250'
        - '30000:32767'
    - role: kubernetes_node_join
      join_command: "{{ hostvars['master'].join_command }}"
  tasks:
    - name: Update apt cache if needed
      apt:
        update_cache: true
        upgrade: safe
        cache_valid_time: 86400

    - name: Ensure NFS Tools installed
      apt:
        name:
          - nfs-client
        state: present
