---
- name: Initial Setup to create ubuntu user
  hosts: all
  become: yes
  
  roles:
    - ubuntu_user
    - docker
    - firewall
    - kubernetes_install
    - nfs

  tasks:

    - name: Create firmware folder
      file:
        path: /boot/firmware
        state: directory
    - name: Set Hostname to inventory_hostname
      hostname:
        name: "{{ inventory_hostname }}"
    - name: Copy the usercfg.txt
      copy:
        src: files/boot/firmware/usercfg.txt
        dest: /boot/firmware/usercfg.txt
    - name: Copy the cmdline.txt
      copy:
        src: files/boot/firmware/cmdline.txt
        dest: /boot/firmware/cmdline.txt

- name: Set up master
  hosts: masters
  become: yes

  roles:
    # - role: nfs_server
    #   user: "ubuntu"
    #   path: "/media/HDD"
    - role: firewall
      ports:
        - '22'
        # There might be some big mistake with this for nfs.
        - '111' # nfs
        - '2049' # nfs
        - '33333' # nfs
        - '40992' # nfs
        - '51461' # nfs
        - '54623' # nfs
        - '56785' # nfs
        - '35996' # nfs
        - '41205' # nfs
        - '179' # BGP
        - '6443' # k8s 
        - '2379:2380' # k8s etcd server client API
        - '10250:10252' # kubelet API, kube-scheduler, kube-controller-manager
    - role: kubernetes_single_control_plane
      ip_address: "192.168.60.4"
      user: vagrant

  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Set up workers
  hosts: workers
  become: yes

  roles:
    - role: firewall
      ports:
        - '22'
        - '179'
        - '10250'
        - '30000:32767'
    - role: kubernetes_node_join
      join_command: "{{ hostvars['master'].join_command }}"
