---
- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add the Docker apt repository
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable
    state: present

- name: Update apt cache if needed
  apt:
    update_cache: true
    upgrade: safe
    cache_valid_time: 86400

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
    state: present

- name: Load overlay module
  community.general.modprobe:
    name: overlay
    state: present

- name: Load br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Copy containerd.conf file
  copy:
    src: files/etc/modules-load.d/containerd.conf
    dest: /etc/modules-load.d/containerd.conf
    mode: 0644

- name: Copy 99-kubernetes-cri.conf file
  copy:
    src: files/etc/sysctl.d/99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    mode: 0644
  register: kubernetes_cri_conf

- name: Apply sysctl params without reboot
  shell: sudo sysctl --system
  when: kubernetes_cri_conf is changed

- name: Create containerd folder
  file:
    path: /etc/containerd
    state: directory

- name: Install containerd
  apt:
    name:
      - containerd
    state: present
  register: containerd_installed

- name: Hold containerd APT Packages
  shell: apt-mark hold containerd
  when: containerd_installed is changed

- name: Copy ontainerd config file
  copy:
    src: files/etc/containerd/config.toml
    dest: /etc/containerd/config.toml
    mode: 0644

- name: Set up the containerd service
  systemd:
    state: started
    masked: no
    name: containerd
    enabled: yes
